### ISSUE TITLE
Sticky Footer

### ISSUE THREAD

**Issue by Toddses** [RainyDayMedia/techhub#12]
Footer should stick to the bottom when the content panel isn't tall enough to push it down. Classic dynamic sticky footer situation.

**Comment by Toddses** [comment]
Turns out its not really a classic sticky footer problem. Its much simpler, and required no javascript.

```css
.footer {
  position: absolute;
  right: 0;
  bottom: 0;
  left: 0;
}
```

Added a margin to the main content panel to push the footer down and create some space between the content and footer. Then just adjust the left/right padding on the footer to position the content correctly.

That simple.
